PackageIdentifier: WashU.Oliver
PackageVersion: 0.1.582
InstallerLocale: en-US
Platform:
  - Windows.Desktop
MinimumOSVersion: 10.0.0.0
InstallerType: nullsoft
Scope: machine
InstallModes:
  - interactive
  - silent
  - silentWithProgress
InstallerSwitches:
  Silent: /S
  SilentWithProgress: /S
ElevationRequirement: elevationRequired
UpgradeBehavior: install
Installers:
  - Architecture: x64
    InstallerUrl: https://github.com/ta-tools/oliver-release/releases/download/v0.1.582/Oliver-Setup-0.1.582-win-x64.exe
    InstallerSha256: 4DBE8B1DFA08F96E6FA2A4CFF0DBC3FDD20B0C81805D93F23F0ABF79BADF51E8
    AppsAndFeaturesEntries:
      - DisplayName: Oliver
        Publisher: Steven Sparks
        ProductCode: Oliver
ManifestType: installer
ManifestVersion: 1.6.0