PackageIdentifier: WashU.Oliver
PackageVersion: 0.1.592
InstallerLocale: en-US
Platform:
  - Windows.Desktop
MinimumOSVersion: 10.0.0.0
InstallerType: nullsoft
Scope: machine
InstallModes:
  - interactive
  - silent
  - silentWithProgress
InstallerSwitches:
  Silent: /S
  SilentWithProgress: /S
ElevationRequirement: elevationRequired
UpgradeBehavior: install
Installers:
  - Architecture: x64
    InstallerUrl: https://github.com/ta-tools/oliver-release/releases/download/v0.1.592/Oliver-Setup-0.1.592-win-x64.exe
    InstallerSha256: 6C31FE3A5697B912C8893540F1B0BEE5289E5F0281CEDCF45BFDE47D395F6101
    AppsAndFeaturesEntries:
      - DisplayName: Oliver
        Publisher: Steven Sparks
        ProductCode: Oliver
ManifestType: installer
ManifestVersion: 1.6.0